# SOPS configuration for nix secrets
# Uses the age key for secrets encryption/decryption
keys:
  - &bartsmykla age1c459u9ehvrjrsh6v2sun69mw3p6apuku8cjh9q8eeax2etr439pshvnn4z

creation_rules:
  - path_regex: .*\.yaml$
    key_groups:
      - age:
          - *bartsmykla
